### ISSUE TITLE
Missing features of integration test framework

### ISSUE THREAD

**Issue by waynexia** [CeresDB/ceresdb#114]
**List**

- Interceptor
  - [x] support `ignore` interceptor #107 
  - [ ] support `echo` interceptor
  - [ ] able to handle random things https://github.com/CeresDB/ceresdb/issues/114#issuecomment-1218949297
- UI
  - [ ] can only run specified cases
  - [ ] redirect server's log to the specified place
  - [ ] Keep original SQL indents
- Runner
  - [ ] customizable config file in dir level (e.g. `tests/cases/config.toml` and `tests/cases/01_dummy/config.toml`)

**Additional context**

**Comment by waynexia** [comment]
>List below are features I want to have:

Updated to the description 👍

**Comment by jiacai2050** [comment]
This test framework is migrated to https://github.com/CeresDB/sqlness, and this issue is kinds of stale, so close it.

New issues can be created in new repo.
