### ISSUE TITLE
Tracking issue of default value support for columns

### ISSUE THREAD

**Issue by ygf11** [CeresDB/ceresdb#252]
### Describe This Problem

 Support default value for columns in Ceresdb.

### Proposal

Support default value:

* Column default value option can be a normal Expr.
* Column can reference other columns, regardless what defining orders they are.

As @ShiKaiWi and @jiacai2050 suggest, the full feature is complex, I split it into some small tasks.

- [ ] https://github.com/CeresDB/ceresdb/issues/249
- [ ] https://github.com/CeresDB/ceresdb/issues/250
- [ ] https://github.com/CeresDB/ceresdb/issues/241

### Additional Context

original issue:
- [ ] https://github.com/CeresDB/ceresdb/issues/210
