### ISSUE TITLE
RFC tracker for wal on kafka

### ISSUE THREAD

**Issue by Rachelint** [CeresDB/ceresdb#280]
### Describe This Problem

When using ceresdb of cluster mode, a distributed wal is needed. Although a distributed wal implementation based on oceanbase has existed but the oceanbase cluster is not so easy to build and maintain, I proposal to implement another distributed wal based on kafka.

### Proposal

see [rendered](https://github.com/Rachelint/ceresdb/blob/wal-kafka-rfc/docs/rfcs/20221007-wal-on-kafka.md)

### Additional Context

The development plan as follow:

- [x] Pass the shard info
- [x] Message queue and its Kafka implementation
- [ ] Replayer and log's splitting
    - [ ] Add a `ShardBasedImpl` to `WalManager`(split to read, merge to write)
    - [ ] Add a replayer to intergrate all the table recovering logics
- [ ] `WalManager` 's message queue implementation
    - [x] Async inner iterator in `BatchLogIteratorAdapter` 
    - [ ] Message queue implementation
