### ISSUE TITLE
Tracking issue for query performance

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/ceresdb#363]
### Describe This Problem

For now, the main bottleneck within a query is sst scan, there are several improvement can be made to accelerate scan process:
- [x] Cache, as described in #312, the row-group level cache is broken, the async reader fix this but has performance regression, we need to investigate this
- [x] min/max filter is broken in main, #360 fix this
- [x] min/max filter may not enough for columns with high cardinality, in this case bloom filter may be a better choice

### Proposal

As above.

### Additional Context

https://github.com/apache/parquet-format/blob/master/BloomFilter.md
