### ISSUE TITLE
Tracking issue: Introduce proxy module

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#681]
### Describe This Problem

Currently, it is just a simple module called `forwarder` that forwards the sql query to the right server, but more work can't be handled by the `forwarder`, including:
- Forward according to the sql rather than the table hints in the sql query;
- Forward all the requests besides the sql query;
- Able to finish query/write about the partitioned table;

### Proposal

Design a proxy module which can serve as a separate service or a module in the ceresdb-server.

**Comment by chunshao90** [comment]
Support automatic table creation in proxy.

**Comment by jiacai2050** [comment]
> Forward according to the sql rather than the table hints in the sql query;

SQL may not enough, other query language should also be supported.

**Comment by chunshao90** [comment]
I am going to introduce the proxy module, and all protocol layers request the proxy module. The proxy module supports `Forword`, `Auth`, `PartitionTable` query.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/15178480/223653720-d92e0992-a61b-457f-b58f-25254fdc1964.png">

**Comment by chunshao90** [comment]
I split the work into the following tasks:

- [ ] The proxy module first supports storage service.
- [ ] Integrate forward in proxy.
- [ ] The proxy module supports mysql service.
- [ ] The proxy module supports http service.
